### PR TITLE
feat: use types and classes

### PR DESCRIPTION
**Pull request by bufferoverflow**

### CODE REVIEW

**Comment by bufferoverflow** [comment]
@juanpicado as discussed over [here](https://github.com/bufferoverflow/verdaccio-gitlab/pull/18#discussion_r186518808), I like to introduce es6 classes. I followed the verdaccio direction and used flow. Still a learning curve and some doubts why flow and not typescript... Any feedback would be appreciated.

**Comment by dlouzan** [comment]
Hello guys, I have just run this branch on my local env and it mainly works, but there's a couple of issues I found:
- The current eslint configuration does not play nice with the new flow setup. I'm still learning about flow and I couldn't make it work properly in WebStorm nor lint, but it will definitely need some adaptations. See https://www.npmjs.com/package/eslint-plugin-flowtype
- The httperror import is wrong in the new babel transpiled syntax, it should be:
  `import httperror from 'http-errors';`. Additionally, I think `http-errors` should be explicitly added to `package.json`
- I'm almost sure that the usage of `forEach` in `allow_publish` will not work as intended, since the code tries to perform a short-circuit of the loop, but this is incorrect [according to the spec](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach). `Array.some` or `Array.reduce` as alternatives, or even a `for...of`

I have contacted @bufferoverflow for guidance, since I'm not sure if it's better to just merge this and continue further changes directly in master.

**Comment by bufferoverflow** [comment]
@dlouzan thanks for the review, I merge this and looking forward for further PRs .

**Comment by juanpicado** [comment]
Sorry @bufferoverflow I missed this thread 😞 ... too late.

**Pull request merged**
