### PR TITLE
chore(deps): less restrictive verdaccio dep in pkg, update dockerfile for verdaccio 4.x stable

### PR DESCRIPTION
**Pull request by StevenLangbroek**
The caret allows for patch & (backwards compatible) minor version updates. Would this also solve the version issue we're seeing [here](https://github.com/bufferoverflow/verdaccio-gitlab/issues/75#issuecomment-505824453)?

### CODE REVIEW

**Comment by StevenLangbroek** [comment]
Question: shouldn't `verdaccio` be a `peerDep` instead of a regular one?

**Comment by dlouzan** [comment]
I'm ok with this, @bufferoverflow please take a look

**Comment by StevenLangbroek** [comment]
@bufferoverflow could you publish this to dockerhub too? 😇 thanks in advance!

**Comment by bufferoverflow** [comment]
@StevenLangbroek latest is now available, see https://hub.docker.com/r/bufferoverflow/verdaccio-gitlab/tags

**Pull request merged**
