### PR TITLE
refactor(dockerfile): builder multistage pattern & random uid user support

### PR DESCRIPTION
**Pull request by dlouzan**
- build image based on current upstream verdaccio refactor, only
  building the plugin code and then symlinking the plugin code
- randomized uid support (e.g. openshift)
- plugin install directory is read-only

### CODE REVIEW

**Comment by dlouzan** [comment]
Please note: this build depends on the work being done in verdaccio under https://github.com/verdaccio/verdaccio/pull/864, in order to build this, it's needed to create a manual build of that verdaccio's PR and manually tag it:

```bash
# In verdaccio PR #864
cd ..
yarn build:docker
docker tag verdaccio:latest verdaccio/verdaccio:3.3

# Now build this image
cd ...
yarn build:docker
# available as verdaccio-gitlab:latest
```

**Comment by dlouzan** [comment]
I'm changing this to make it depend on verdaccio/verdaccio:4.x-next. But until the changes in the pending PR in verdaccio for refactored dockerfile are applied, this won't work unless we build manually locally (see comment above)

**Comment by juanpicado** [comment]
It's out
```
docker pull verdaccio/verdaccio:4.x-next
````

**Comment by bufferoverflow** [comment]
This is great! 

Please seperate the fixes for gitlab.js and package.json into a dedicated PR as they are not related to the docker build.

**Pull request merged**
