### PR TITLE
refactor: migrating to typescript 3.7

### PR DESCRIPTION
**Pull request by juanpicado**
Open questions before start this development: @dlouzan @bufferoverflow 

- [x]  preset setup
- [x]  eslint setup
- [x] fix lint issues
- [x] tests

refers to https://github.com/bufferoverflow/verdaccio-gitlab/issues/83

At verdaccio organization we have 

```
 "@verdaccio/babel-preset": "0.2.1",
  "@verdaccio/eslint-config": "0.0.1",
```

which is a easy way to share config all over the projects, all can be overwritten for customize some settings.  Do you want to be part of this? or rather a raw configuration and keep the control of it?

Examples:
https://github.com/verdaccio/verdaccio-aws-s3-storage/blob/master/.eslintrc
https://github.com/verdaccio/verdaccio-aws-s3-storage/blob/master/.babelrc

About presets, I've noticed the target is `current`, I'd not recommend this approach since this might depends of which Node.js is installed in the dev machine, I'd suggest here a value, in my case we support >=8.

cc: @dlouzan @bufferoverflow

### CODE REVIEW

**Comment by juanpicado** [comment]
Just a reminder @dlouzan @bufferoverflow I need your feedback 🙃 on my questions above.

**Comment by bufferoverflow** [comment]
@juanpicado sorry for the delay! I‘m absolutely fine with the verdaccio defaults. This is a plugin and should be in-line with verdaccio style and best practices.

**Comment by juanpicado** [comment]
Ok guys :) let me know whether something else is missing

**Comment by bufferoverflow** [comment]
@juanpicado sorry for the delay! Look really good. I do some local testing tomorrow before merging.

**Comment by bufferoverflow** [comment]
@juanpicado I just tested it, works like a charm! Just two minor things I would appreciate, add `lint:ts` to the .travis.yml and get rid of the warnings emitted by `lint:ts`

**Comment by juanpicado** [comment]
Sure I will @bufferoverflow 🚀

**Comment by juanpicado** [comment]
@bufferoverflow actually the lint is more complete due that check types

```
"lint": "yarn type-check && yarn lint:ts && eclint check $(git ls-files) && markdownlint README.md",
```
The `yarn type-check` step is really important.

**Comment by juanpicado** [comment]
I get rid of `eclint` due prettier does the job now.

**Comment by bufferoverflow** [comment]
@juanpicado Thank you so much!

**Comment by juanpicado** [comment]
It was a pleasure ❤️

**Pull request merged**
