### PR TITLE
feat: add project groups

### PR DESCRIPTION
**Pull request by jstarry**
References: https://github.com/bufferoverflow/verdaccio-gitlab/issues/63

If a Gitlab user is a maintainer of a project but not a maintainer of the group that the project is in, they should still have publish rights.

### CODE REVIEW

**Comment by jstarry** [comment]
@dlouzan would you mind looking over this PR? Thanks 👍

**Comment by jstarry** [comment]
Cool! Thank you @bufferoverflow for creating this plugin, it's just what we needed 👍

**Comment by bufferoverflow** [comment]
@dlouzan Could you review this as well and merge if you agree on it?

**Comment by dlouzan** [comment]
This is a great PR, I'm currently checking the code but it really looks great

**Comment by dlouzan** [comment]
This makes perfect sense. The use of two Gitlab API calls should be completely ok under high load by using the cache.

Your code is actually much more elegant and I love how you used `Promise.all` and the spread operator to join the results.

LGTM :+1:

**Pull request merged**
