### PR TITLE
chore: use verdaccio 4 instead of 4.0 within Dockerfile

### PR DESCRIPTION
**Pull request by bufferoverflow**

### CODE REVIEW

**Comment by dlouzan** [comment]
@bufferoverflow I'll do a local test, about this one I'm not that sure it will work without code changes. I remember reading at some point that the API in the newer 4.x versions was different. I can't find the reference right now though...

**Comment by dlouzan** [comment]
@bufferoverflow I'm getting exceptions on build, though I'm not sure if this is my local setup :-?

```
(chore/use-verdaccio-4 $= abd814e)$ yarn build:docker
yarn run v1.19.2
$ docker build -t verdaccio-gitlab . --no-cache
Sending build context to Docker daemon  2.938MB
Step 1/15 : FROM node:10-alpine as builder
 ---> 27d9cbdc7319
Step 2/15 : WORKDIR /opt/verdaccio-gitlab-build
 ---> Running in 2477bd6d012c
Removing intermediate container 2477bd6d012c
 ---> 18c7f898f272
Step 3/15 : COPY . .
 ---> 343202b04719
Step 4/15 : ENV NODE_ENV=production     VERDACCIO_BUILD_REGISTRY=https://registry.npmjs.org/
 ---> Running in bea32d3fd94c
Removing intermediate container bea32d3fd94c
 ---> 4a2196c9e81f
Step 5/15 : RUN yarn config set registry $VERDACCIO_BUILD_REGISTRY &&     yarn install --production=false &&     yarn code:docker-build &&     yarn cache clean &&     yarn install --production=true --pure-lockfile
 ---> Running in ad353712a720
yarn config v1.7.0
success Set "registry" to "https://registry.npmjs.org/".
Done in 0.12s.
yarn install v1.7.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
(node:26) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
error @typescript-eslint/eslint-plugin@2.6.1: The engine "node" is incompatible with this module. Expected version "^8.10.0 || ^10.13.0 || >=11.10.1".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn config set registry $VERDACCIO_BUILD_REGISTRY &&     yarn install --production=false &&     yarn code:docker-build &&     yarn cache clean &&     yarn install --production=true --pure-lockfile' returned a non-zero code: 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by dlouzan** [comment]
Which btw tells me that we should add the docker build step to CI

**Comment by bufferoverflow** [comment]
```
yarn build:docker
yarn run v1.21.0
$ docker build -t verdaccio-gitlab . --no-cache
Sending build context to Docker daemon  982.5kB
Step 1/15 : FROM node:10-alpine as builder
 ---> 8cb0238efebf
Step 2/15 : WORKDIR /opt/verdaccio-gitlab-build
 ---> Running in b30c59501560
Removing intermediate container b30c59501560
 ---> 9854279d2653
Step 3/15 : COPY . .
 ---> 5385196f5565
Step 4/15 : ENV NODE_ENV=production     VERDACCIO_BUILD_REGISTRY=https://registry.npmjs.org/
 ---> Running in 0f32a53557d6
Removing intermediate container 0f32a53557d6
 ---> 8a2b87ffa626
Step 5/15 : RUN yarn config set registry $VERDACCIO_BUILD_REGISTRY &&     yarn install --production=false &&     yarn code:docker-build &&     yarn cache clean &&     yarn install --production=true --pure-lockfile
 ---> Running in 7eb9090d57e2
yarn config v1.21.1
success Set "registry" to "https://registry.npmjs.org/".
Done in 0.09s.
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @typescript-eslint/eslint-plugin@2.6.1" has unmet peer dependency "@typescript-eslint/parser@^2.0.0".
[5/5] Building fresh packages...
$ in-publish && yarn lint && yarn code:build || not-in-publish
Done in 53.25s.
yarn run v1.21.1
$ cross-env BABEL_ENV=docker babel src/ --out-dir build/ --extensions ".ts,.tsx"
Successfully compiled 4 files with Babel.
Done in 1.06s.
yarn cache v1.21.1
success Cleared cache.
Done in 3.95s.
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @typescript-eslint/eslint-plugin@2.6.1" has unmet peer dependency "@typescript-eslint/parser@^2.0.0".
[5/5] Building fresh packages...
Done in 42.83s.
Removing intermediate container 7eb9090d57e2
 ---> 79c12fd3a5a1
Step 6/15 : FROM verdaccio/verdaccio:4
 ---> 26437de00509
Step 7/15 : LABEL maintainer="https://github.com/bufferoverflow/verdaccio-gitlab"
 ---> Running in 762c150a6ee8
Removing intermediate container 762c150a6ee8
 ---> d1e48166d510
Step 8/15 : USER root
 ---> Running in d0213e41b6c7
Removing intermediate container d0213e41b6c7
 ---> ab313e9e7f0c
Step 9/15 : COPY --from=builder /opt/verdaccio-gitlab-build/build /opt/verdaccio-gitlab/build
 ---> d4848e0586e4
Step 10/15 : COPY --from=builder /opt/verdaccio-gitlab-build/package.json /opt/verdaccio-gitlab/package.json
 ---> 641af584a50c
Step 11/15 : COPY --from=builder /opt/verdaccio-gitlab-build/node_modules /opt/verdaccio-gitlab/node_modules
 ---> 741c8576812c
Step 12/15 : ADD conf/docker.yaml /verdaccio/conf/config.yaml
 ---> b3252c8a341b
Step 13/15 : WORKDIR $VERDACCIO_APPDIR
 ---> Running in ae055e57a056
Removing intermediate container ae055e57a056
 ---> c5bba24e40db
Step 14/15 : RUN ln -s /opt/verdaccio-gitlab/build /verdaccio/plugins/verdaccio-gitlab
 ---> Running in 2350f989087e
Removing intermediate container 2350f989087e
 ---> e3a869661ef3
Step 15/15 : USER $VERDACCIO_USER_UID
 ---> Running in cba238d5ce3c
Removing intermediate container cba238d5ce3c
 ---> 710f63eb21cd
Successfully built 710f63eb21cd
Successfully tagged verdaccio-gitlab:latest
✨  Done in 134.34s.
```

```

$ docker --version && node --version && yarn --version
Docker version 19.03.5, build 633a0ea
v12.13.1
1.21.0
```

**Comment by bufferoverflow** [comment]
@dlouzan I just added the docker build to ci

**Comment by dlouzan** [comment]
@bufferoverflow Thanks for the feedback. Turns out it was my own (broken) yarn installation.

I was able to build, start everything with docker-compose and push a package 👍

**Pull request merged**
