### PR TITLE
fix: pass true to callback for allowed perms in allow_publish

### PR DESCRIPTION
**Pull request by apoleshchuk**

### CODE REVIEW

**Comment by dlouzan** [comment]
Thank you, yes, most probably it should return true on successful authentication.

I'm curious, is this just cosmetic or are you observing any issues with the plugin behaviour returning `(null, false)` on succes? As far as I understand, as long as we don't return an error in the first parameter, verdaccio is happy with it.

**Comment by apoleshchuk** [comment]
> I'm curious, is this just cosmetic or are you observing any issues with the plugin behaviour returning `(null, false)` on succes? As far as I understand, as long as we don't return an error in the first parameter, verdaccio is happy with it.

I try verdaccio-gitlab for main auth plugin. Without `true` state in callback verdaccio go-to next plugin for check permissions: https://github.com/verdaccio/verdaccio/blob/master/src/lib/auth.js#L162

**Comment by dlouzan** [comment]
You are right, but this has implications. I'm reviewing our code and we are returning (inconsistently) true for `allow_access` and false for `allow_publish` on successful authentication.

As I understand the verdaccio code in both `allow_access` and `allow_publish`:
- returning `(null, true)` will short-circuit the plugins evaluation and execute the successful callback
- returning `(null, false)` will be successful but delegate to the next plugin in the chain

@bufferoverflow The implication of returning `true` is that we stop the evaluation of further plugins on the chain. I'm ok with it, but I'd like to hear your view.

@juanpicado Although it's documented in the code, I haven't seen this explained in the [plugins documentation](https://verdaccio.org/docs/en/dev-plugins). Is the behaviour as explained above correct? i could add a PR to extend the docs.

**Comment by bufferoverflow** [comment]
The correct behavior from my perspective is:
> returning (null, false) will be successful but delegate to the next plugin in the chain

**Comment by juanpicado** [comment]
> Although it's documented in the code, I haven't seen this explained in the plugins documentation. Is the behavior as explained above correct? i could add a PR to extend the docs

@dlouzan sorry I'm late to the party (I was 🏖 ) yes, you are right, the doc is not perfect, worth to extend it. But I'd suggest a small update, I was thinking who to display a better plugin documentation. Suggestions are welcome.

Aside from that, agree with @bufferoverflow .

**Comment by bufferoverflow** [comment]
@apoleshchuk could you adopt the tests as well?

**Comment by dlouzan** [comment]
@juanpicado No worries, I hope you recharged batteries :-)

> But I'd suggest a small update, I was thinking who to display a better plugin documentation. Suggestions are welcome.

I don't understand this. What do you mean with *who*? do you mean *how*? are you asking for a refactoring of the plugin documentation?

**Comment by dlouzan** [comment]
I will create a ticket to check this part of the code, we definitely have inconsistent behavior between `allow_access` and `allow_publish`. I'm ok with allowing the chain of plugins to be applied in both cases (returning `false`), but I'm not sure if there's any side effect.

@apoleshchuk Why is it an issue for you that the plugin follows the chain and returns `false`, allowing further plugins to have a say? Could you please elaborate on your use case for needing to return `true`?

I will close this ticket for the moment, we can re-open if needed.

**Comment by dlouzan** [comment]
@apoleshchuk For your information, we are rolling back the returning of `false` and now return back `true` again, at least until https://github.com/verdaccio/verdaccio/issues/1120 is resolved

**Comment by apoleshchuk** [comment]
@dlouzan thanks. When this fix released in npm?

**Comment by dlouzan** [comment]
@bufferoverflow Are you ok with releasing a 2.1.0 with the latest changes?

**Comment by bufferoverflow** [comment]
@dlouzan yes of course, could you provide me your name on https://www.npmjs.com so you can publish it.

**Comment by dlouzan** [comment]
@bufferoverflow Same as here, just registered: `dlouzan`

**Comment by bufferoverflow** [comment]
@dlouzan just added you, so you can create a release.

**Comment by dlouzan** [comment]
@apoleshchuk v2.1.0 has been just released.

**Pull request closed without merging**
