### PR TITLE
fix: Allows matching of mixed-case usernames

### LINKED ISSUE #20: Uppercase authentication issue
It seems you check the username in the login with case sensitivity

NPM CLI ask you to login with a lowercase username
Gitlab doesn't allow you to have the same username with a different case

So if you have an username with an uppercase, you can login in the Web UI but not in the CLI.

### PR DESCRIPTION
**Pull request by lando-cal**
Fixes #20 
GitLab will now return a user through case-agnostic matching, so I updated a line to accommodate this within the plugin.

### CODE REVIEW

**Comment by bufferoverflow** [comment]
@lando-cal thanks for the contribution! Couold you rebase to master as we switched to typescript recently? btw. the build fails because of capital letter, this should work: `fix: allows matching of mixed-case usernames`

**Comment by dlouzan** [comment]
@lando-cal Also would you mind linking to the issue when / where this change was applied to gitlab? I quick search in Google did not show me this `¯\_(ツ)_/¯`

**Comment by lando-cal** [comment]
I can re-base in the next day or two, no problem. 

As far as a link, that I can't provide. Haha. I was just taking the word of the OP that it didn't work before. I had attempted the login with a mixed case account, in lowercase, and it resolved fine, then I updated the code and published it internally and it's been working fine this far. 

It wasn't until going to submit the fix that I noticed the other ticket..

So, I suppose it could have been working before and it was overlooked, or perhaps I'm misinterpreting the concerns, but this is currently working for us in our dev environments.

⁣Get BlueMail for Android ​

**Comment by GFWagnitz** [comment]
@bufferoverflow  Any news on merging this? The solution actually solves a huge problem and since it's not merged I had to fork the project to implement the same solution.

**Comment by bufferoverflow** [comment]
@GFWagnitz This cannot be merged, see https://github.com/bufferoverflow/verdaccio-gitlab/pull/96#issuecomment-554910096 , we also like to see an answer for https://github.com/bufferoverflow/verdaccio-gitlab/pull/96#issuecomment-555588527  feel free to create a new PR if it's based on latest master.

**Comment by lando-cal** [comment]
A bit unfortunate that I was unable to get a contribution credit on this. None the less, thank you all for making sure the resolution went upstream!

**Comment by bufferoverflow** [comment]
@lando-cal We all appriciate your work and contribution!

**Pull request closed without merging**
