### PR TITLE
clarify publish options

### PR DESCRIPTION
**Pull request by slhck**
Clarify the documentation in terms of what has to be configured and who, consequently, has access to what.

### CODE REVIEW

**Comment by bufferoverflow** [comment]
@slhck I would appriciate if you could use conventional changelog for the commit message, so I can merge this valuable contribution.

**Comment by slhck** [comment]
Tried to do so. I have never used conventional changelog so I assume that this works.

**Comment by bufferoverflow** [comment]
@slhck commit message is good, but now markdown lint complains:

```
yarn lint
yarn run v1.15.2
$ yarn type-check && yarn lint:ts && markdownlint README.md
$ tsc --noEmit
$ eslint . --ext .js,.ts
README.md:117 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 3]
README.md:118 MD013/line-length Line length [Expected: 80; Actual: 133]
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command "yarn lint" exited with 1.
```

**Comment by slhck** [comment]
Ugh. I just wanted to provide a simple fix. Should be okay now.

**Comment by bufferoverflow** [comment]
@slhck thanks a lot! one reason for doing conventional changelog is simplify release process, see https://github.com/bufferoverflow/verdaccio-gitlab#create-a-release , the https://github.com/bufferoverflow/verdaccio-gitlab/blob/master/CHANGELOG.md is automatically generated.

**Pull request merged**
